version: 2.1

##################################################################
# WORFLOWS
##################################################################
workflows:
  despliegue_a_master:
    jobs:
      - creacion_de_docker:
          filters:
            branches:
              only: master

      - despliegue_a_heroku:
          requires:
            - creacion_de_docker
          filters:
            branches:
              only: master


##################################################################
# EXECUTORS
##################################################################
executors:
  ejecutor-base:
    machine:
      enabled: true
    working_directory: ~/proyect


##################################################################
# JOBS
##################################################################
jobs:
  
  creacion_de_docker:
    executor: ejecutor-base
    steps:
      - attach_workspace:
          at: ~/proyect
      - checkout
      - run:
          name: buildear imagen
          command: |
            DOCKER_TAG=${CIRCLE_SHA1:0:7}
            . scripts/docker/build.sh
      - run:
          name: pushear nueva version
          command: |
            DOCKER_TAG=${CIRCLE_SHA1:0:7}
            . scripts/docker/push.sh
      - run:
          name: pushear nueva latest
          command: |
            DOCKER_TAG=${CIRCLE_SHA1:0:7}
            . scripts/docker/push-latest.sh


  despliegue_a_heroku:
    executor: ejecutor-base
    steps:
      - attach_workspace:
          at: ~/proyect
      - checkout
      - run:
          name: instalar heroku
          command: . scripts/heroku-docker/install-heroku.sh
      - run:
          name: generar dockerfile
          command: |
            DOCKER_TAG=${CIRCLE_SHA1:0:7}
            scripts/heroku-docker/build-dockerfile.sh
      - run:
          name: agregar CMD con $PORT
          command: |
            echo "CMD gunicorn -b 0.0.0.0:\$PORT app:app" >> Dockerfile
      - run:
          name: despliegue
          command: |
            DOCKER_TAG=${CIRCLE_SHA1:0:7}
            . scripts/heroku-docker/deploy.sh
